export const LOC_DEFS = {
  camp:             { name: "Forladt lejr",      emoji: "?", trig: 130, maxE: 2, goldR: [0, 3],  wRar: [0, 1], etype: ["imp"],           vagrants: 2 },
  wagon:            { name: "Odelagt vogn",      emoji: "?", trig: 110, maxE: 2, goldR: [1, 4],  wRar: [0, 1], etype: ["imp"],           vagrants: 1 },
  grave:            { name: "Gammel grav",       emoji: "?", trig: 90,  maxE: 1, goldR: [0, 2],  wRar: [0, 1], etype: ["imp"],           vagrants: 0 },
  ruins:            { name: "Ruiner",            emoji: "?", trig: 150, maxE: 3, goldR: [2, 6],  wRar: [1, 2], etype: ["imp"],           vagrants: 2 },
  cave:             { name: "Grotte",            emoji: "?", trig: 130, maxE: 4, goldR: [4, 10], wRar: [1, 2], etype: ["imp", "fireImp"], vagrants: 1 },
  battlefield:      { name: "Gammel slagmark",   emoji: "?", trig: 180, maxE: 5, goldR: [3, 8],  wRar: [1, 2], etype: ["imp", "fireImp"], vagrants: 3 },
  watchtower:       { name: "Vagttarn",          emoji: "?", trig: 140, maxE: 4, goldR: [2, 6],  wRar: [2, 3], etype: ["imp", "fireImp"], vagrants: 1 },
  altar:            { name: "Mystisk alter",     emoji: "?", trig: 120, maxE: 6, goldR: [0, 5],  wRar: [2, 3], etype: ["fireImp"],       vagrants: 0 },
  shack:            { name: "Forladt hytte",     emoji: "?", trig: 100, maxE: 2, goldR: [0, 3],  wRar: [0, 1], etype: ["imp"],           vagrants: 1 },
  ruinedwatchtower: { name: "Ruineret vagttarn", emoji: "?", trig: 160, maxE: 4, goldR: [2, 7],  wRar: [1, 2], etype: ["imp", "fireImp"], vagrants: 1 },
  shrine:           { name: "Glempt helligdom",  emoji: "?", trig: 140, maxE: 5, goldR: [1, 5],  wRar: [2, 3], etype: ["fireImp"],       vagrants: 0 },
  huntingstand:     { name: "Jagtstativ",        emoji: "?", trig: 120, maxE: 3, goldR: [1, 4],  wRar: [0, 1], etype: ["imp"],           vagrants: 0 },
  mill:             { name: "Molle",             emoji: "?", trig: 130, maxE: 3, goldR: [2, 5],  wRar: [1, 1], etype: ["imp"],           vagrants: 1 },
  fallenTree:       { name: "Faeldet trae",      emoji: "?", trig: 110, maxE: 2, goldR: [1, 3],  wRar: [0, 1], etype: ["imp"],           vagrants: 0 },
  abandonedfort:    { name: "Forladt fort",      emoji: "?", trig: 170, maxE: 5, goldR: [3, 8],  wRar: [1, 2], etype: ["imp", "fireImp"], vagrants: 2 },
};
