export const LOC_DEFS = {
  camp:             { name: "Abandoned camp",      emoji: "?", trig: 130, maxE: 2, goldR: [0, 3],  wRar: [0, 1], etype: ["imp"],           vagrants: 2 },
  wagon:            { name: "Wrecked wagon",      emoji: "?", trig: 110, maxE: 2, goldR: [1, 4],  wRar: [0, 1], etype: ["imp"],           vagrants: 1 },
  grave:            { name: "Old grave",       emoji: "?", trig: 90,  maxE: 1, goldR: [0, 2],  wRar: [0, 1], etype: ["imp"],           vagrants: 0 },
  ruins:            { name: "Ruins",            emoji: "?", trig: 150, maxE: 3, goldR: [2, 6],  wRar: [1, 2], etype: ["imp"],           vagrants: 2 },
  cave:             { name: "Cave",            emoji: "?", trig: 130, maxE: 4, goldR: [4, 10], wRar: [1, 2], etype: ["imp", "fireImp"], vagrants: 1 },
  battlefield:      { name: "Old battlefield",   emoji: "?", trig: 180, maxE: 5, goldR: [3, 8],  wRar: [1, 2], etype: ["imp", "fireImp"], vagrants: 3 },
  watchtower:       { name: "Watchtower",          emoji: "?", trig: 140, maxE: 4, goldR: [2, 6],  wRar: [2, 3], etype: ["imp", "fireImp"], vagrants: 1 },
  altar:            { name: "Mysterious altar",     emoji: "?", trig: 120, maxE: 6, goldR: [0, 5],  wRar: [2, 3], etype: ["fireImp"],       vagrants: 0 },
  shack:            { name: "Abandoned shack",     emoji: "?", trig: 100, maxE: 2, goldR: [0, 3],  wRar: [0, 1], etype: ["imp"],           vagrants: 1 },
  ruinedwatchtower: { name: "Ruined watchtower", emoji: "?", trig: 160, maxE: 4, goldR: [2, 7],  wRar: [1, 2], etype: ["imp", "fireImp"], vagrants: 1 },
  shrine:           { name: "Forgotten shrine",  emoji: "?", trig: 140, maxE: 5, goldR: [1, 5],  wRar: [2, 3], etype: ["fireImp"],       vagrants: 0 },
  huntingstand:     { name: "Hunting stand",        emoji: "?", trig: 120, maxE: 3, goldR: [1, 4],  wRar: [0, 1], etype: ["imp"],           vagrants: 0 },
  mill:             { name: "Mill",             emoji: "?", trig: 130, maxE: 3, goldR: [2, 5],  wRar: [1, 1], etype: ["imp"],           vagrants: 1 },
  fallenTree:       { name: "Fallen tree",      emoji: "?", trig: 110, maxE: 2, goldR: [1, 3],  wRar: [0, 1], etype: ["imp"],           vagrants: 0 },
  abandonedfort:    { name: "Abandoned fort",      emoji: "?", trig: 170, maxE: 5, goldR: [3, 8],  wRar: [1, 2], etype: ["imp", "fireImp"], vagrants: 2 },
};
