export const Game = {
  state: "menu",
  time: 0,
  day: 1,
  isNight: false,
  cam: 0,
  treeSeed: 12345,
  spawnTimer: 0,
  nightQuota: 0,
  nightSpawned: 0,
  nightCleared: false,
  wasNight: false,
  threatLevel: 1,
  autosaveTimer: 0,
  windT: 0,
  inventoryOpen: false,
  wallSlots: {},
  shopOpen: false,
  shopIdx: 0,
  shopTab: 0,
  castleOpen: false,
  castleIdx: 0,
  difficulty: "normal",
  diffMult: 1.0,
  targetFps: 120,
  upgradeMenuOpen: false,
  upgradeOptions: null,
  upgradeIdx: 0,
  zoom: 1.2,
  legendaryIntro: null,
  screenShake: 0,
  skillTreeType: "archer",
  meta: null,
  runKills: 0,
  hubMessage: "",
  hubT: 0,
  hubTransitionT: 0,
  hubTransitionFromX: 0,
  runStartAnim: 0,
  killStreak: 0,
  killStreakTimer: 0,
  momentumLevel: 0,
  momentumTimer: 0,
  lastStandDay: 0,
  nightPortalWarnT: 0,
  activeBiome: "forest",  // the entire run world uses one biome at a time
  unlockedBiomes: ["forest"],
  worldPhase: 1,          // 1 = Ashen Reign, 2 = the Hollow (after the final biome)
  phaseTransition: null,  // { t, swapped } while the phase-2 flash plays
  oneSidedNightSide: null, // -1|1 while tonight's attacks only come from one portal side, else null
  oneSidedAnnounce: null,  // { timer, maxTimer, side } banner shown at nightfall
  bountyRaidersRemaining: 0,
};

// All mutable entity arrays and per-play variables live here so every
// module shares the same references without relying on global scope.
export const state = {
  player: null,
  base: null,
  units: [],
  vagrants: [],
  enemies: [],
  coins: [],
  goldCollectors: [],
  arrows: [],
  animals: [],
  walls: [],
  particles: [],
  floatTexts: [],
  portals: [],
  stations: [],
  lootItems: [],
  chests: [],
  weaponPickup: null,
  forestTrees: [],
  forestCamps: [],
  ponds: [],
  groundBows: [],
  groundHammers: [],
  spells: [],
  spellFields: [],
  vagrantTimer: 1,
  animalTimer: 2,
  pendingHammers: 0,
  pendingFarmers: 0,
  farmBuilt: false,
  farmLevel: 0,
  poisonShots: [],
  caltrops: [],
  archerSkillPoints: 0,
  archerSkills: [],
  arrowRainCd: 0,
  guardSkillPoints: 0,
  guardSkills: [],
  rallyCd: 0,
  rallyT: 0,
  payCooldown: 0,
  payHoldTime: 0,
  lastPaidStation: null,
  legendaryBoss: null,
  legendaryEffects: [],
  aegisStrikes: [],
  firePools: [],
  beacon: null,
  assault: null, // active portal assault ({ phase, portal, ... }) or null
  castleUpgrades: { masonry: 0, garrison: 0, treasury: 0, aegis: 0 },
};
