export const Game = {
  state: "menu",
  time: 0,
  day: 1,
  isNight: false,
  cam: 0,
  treeSeed: 12345,
  spawnTimer: 0,
  nightQuota: 0,
  nightSpawned: 0,
  wasNight: false,
  goalReached: false,
  surviveNightForWin: false,
  winNightActive: false,
  pendingWin: false,
  autosaveTimer: 0,
  windT: 0,
  inventoryOpen: false,
  wallSlots: {},
  shopOpen: false,
  shopIdx: 0,
  diffMult: 1.0,
  rarityBonus: 0,
};

// All mutable entity arrays and per-play variables live here so every
// module shares the same references without relying on global scope.
export const state = {
  player: null,
  base: null,
  units: [],
  vagrants: [],
  enemies: [],
  coins: [],
  arrows: [],
  animals: [],
  walls: [],
  particles: [],
  floatTexts: [],
  portals: [],
  stations: [],
  lootItems: [],
  weaponPickup: null,
  locations: [],
  groundBows: [],
  groundHammers: [],
  vagrantTimer: 1,
  animalTimer: 2,
  pendingHammers: 0,
  pendingFarmers: 0,
  farmBuilt: false,
  payCooldown: 0,
  lastPaidStation: null,
};
